package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
)

type modelInfo struct {
	ID                        string           `json:"id"`
	DisplayName               string           `json:"display_name"`
	MaxInputTokens            int              `json:"max_input_tokens"`
	MaxTokens                 int              `json:"max_tokens"`
	Thinking                  *thinkingSupport `json:"thinking"`
	SupportedInputModalities  []string         `json:"supportedInputModalities"`
	SupportedOutputModalities []string         `json:"supportedOutputModalities"`
}

type thinkingSupport struct {
	Min            int      `json:"min"`
	Max            int      `json:"max"`
	ZeroAllowed    bool     `json:"zero_allowed"`
	DynamicAllowed bool     `json:"dynamic_allowed"`
	Levels         []string `json:"levels"`
}

type modelsResponse struct {
	Data []modelInfo `json:"data"`
}

func (a *app) writeBackendConfig(port int) error {
	quote := func(value string) string { return strconv.Quote(filepath.ToSlash(value)) }
	var aliases strings.Builder
	aliases.WriteString("oauth-model-alias:\n  antigravity:\n")
	for _, alias := range zcodeModelAliases {
		fmt.Fprintf(&aliases, "    - name: %s\n", strconv.Quote(alias.UpstreamID))
		fmt.Fprintf(&aliases, "      alias: %s\n", strconv.Quote(alias.ClientID))
		fmt.Fprintf(&aliases, "      display-name: %s\n", strconv.Quote(alias.DisplayName))
		aliases.WriteString("      force-mapping: true\n")
	}
	content := fmt.Sprintf(`# Generated by ZCode Antigravity Bridge. Edit settings.json, not this file.
host: "127.0.0.1"
port: %d

tls:
  enable: false
  cert: ""
  key: ""

remote-management:
  allow-remote: false
  secret-key: %s
  disable-control-panel: true
  disable-auto-update-panel: true

auth-dir: %s

api-keys:
  - %s

debug: false
commercial-mode: true
logging-to-file: true
logs-max-total-size-mb: 50
error-logs-max-files: 5
request-log: false
usage-statistics-enabled: false
proxy-url: %s
passthrough-headers: false
request-retry: 2
max-retry-credentials: 2
max-retry-interval: 20
save-cooldown-status: false
disable-claude-cloak-mode: true

claude-code:
  disable-cloaking-model-list: true

quota-exceeded:
  switch-project: true
  switch-preview-model: true
  antigravity-credits: false

%s
routing:
  strategy: "round-robin"
  session-affinity: true
  session-affinity-ttl: "2h"

plugins:
  enabled: false
  dir: "plugins"
  configs: {}
`, port, strconv.Quote(a.apiKey), quote(a.paths.AuthDir), strconv.Quote(a.apiKey), strconv.Quote(strings.TrimSpace(a.settings.ProxyURL)), aliases.String())
	return writeAtomic(a.paths.Config, []byte(content), 0o600)
}

func (a *app) gatewayURL(port int) string {
	return fmt.Sprintf("http://127.0.0.1:%d", port)
}

func httpClient(timeout time.Duration) *http.Client {
	return &http.Client{
		Timeout: timeout,
		Transport: &http.Transport{
			Proxy:               http.ProxyFromEnvironment,
			DisableCompression:  false,
			MaxIdleConns:        4,
			IdleConnTimeout:     30 * time.Second,
			TLSHandshakeTimeout: 5 * time.Second,
		},
	}
}

func (a *app) probeGateway(port int) error {
	client := httpClient(1500 * time.Millisecond)
	rootResp, err := client.Get(a.gatewayURL(port) + "/")
	if err != nil {
		return err
	}
	defer rootResp.Body.Close()
	if rootResp.StatusCode != http.StatusOK {
		return fmt.Errorf("根端点返回 HTTP %d", rootResp.StatusCode)
	}
	var root struct {
		Message string `json:"message"`
	}
	if err := json.NewDecoder(io.LimitReader(rootResp.Body, 64<<10)).Decode(&root); err != nil {
		return fmt.Errorf("根端点不是预期 JSON: %w", err)
	}
	if root.Message != "CLI Proxy API Server" {
		return fmt.Errorf("端口上的服务不是 CLI Proxy API")
	}
	healthResp, err := client.Get(a.gatewayURL(port) + "/healthz")
	if err != nil {
		return err
	}
	defer healthResp.Body.Close()
	if healthResp.StatusCode != http.StatusOK {
		return fmt.Errorf("健康检查返回 HTTP %d", healthResp.StatusCode)
	}
	return nil
}

func (a *app) fetchModels(port int) ([]modelInfo, error) {
	req, err := http.NewRequest(http.MethodGet, a.gatewayURL(port)+"/v1/models", nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("x-api-key", a.apiKey)
	req.Header.Set("Authorization", "Bearer "+a.apiKey)
	req.Header.Set("anthropic-version", "2023-06-01")
	req.Header.Set("User-Agent", "ZCode-Antigravity-Bridge/"+version)
	resp, err := httpClient(5 * time.Second).Do(req)
	if err != nil {
		return nil, fmt.Errorf("读取模型列表: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(io.LimitReader(resp.Body, 4<<20))
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("模型列表返回 HTTP %d: %s", resp.StatusCode, compactText(body, 240))
	}
	var payload modelsResponse
	if err := json.Unmarshal(body, &payload); err != nil {
		return nil, fmt.Errorf("模型列表不是预期 JSON: %w", err)
	}
	seen := make(map[string]bool)
	models := make([]modelInfo, 0, len(payload.Data))
	for _, model := range payload.Data {
		model.ID = strings.TrimSpace(model.ID)
		model.DisplayName = strings.TrimSpace(model.DisplayName)
		if model.ID == "" || seen[model.ID] {
			continue
		}
		seen[model.ID] = true
		models = append(models, model)
	}
	sort.Slice(models, func(i, j int) bool { return models[i].ID < models[j].ID })
	return models, nil
}

func compactText(raw []byte, max int) string {
	value := strings.Join(strings.Fields(string(raw)), " ")
	if len(value) > max {
		return value[:max] + "..."
	}
	return value
}

func isPortFree(port int) bool {
	listener, err := net.Listen("tcp4", fmt.Sprintf("127.0.0.1:%d", port))
	if err != nil {
		return false
	}
	_ = listener.Close()
	return true
}

func chooseFreePort(start, end int) (int, error) {
	for candidate := start; candidate <= end; candidate++ {
		if isPortFree(candidate) {
			return candidate, nil
		}
	}
	return 0, fmt.Errorf("端口 %d-%d 全部被占用", start, end)
}

func (a *app) chooseGatewayPort() (port int, reuse bool, err error) {
	current, stateErr := a.loadState()
	if stateErr != nil {
		return 0, false, stateErr
	}
	candidates := make([]int, 0, a.settings.PortScanEnd-a.settings.PreferredPort+2)
	if current.Port >= a.settings.PreferredPort && current.Port <= a.settings.PortScanEnd {
		candidates = append(candidates, current.Port)
	}
	for candidate := a.settings.PreferredPort; candidate <= a.settings.PortScanEnd; candidate++ {
		candidates = append(candidates, candidate)
	}
	seen := make(map[int]bool)
	occupied := make([]string, 0, 4)
	for _, candidate := range candidates {
		if seen[candidate] {
			continue
		}
		seen[candidate] = true
		if err := a.probeGateway(candidate); err == nil {
			if _, authErr := a.fetchModels(candidate); authErr == nil {
				return candidate, true, nil
			}
		}
		if isPortFree(candidate) {
			return candidate, false, nil
		}
		if len(occupied) < 4 {
			occupied = append(occupied, fmt.Sprintf("%d (%s)", candidate, describePortOwner(candidate)))
		}
	}
	return 0, false, fmt.Errorf("端口 %d-%d 全部被占用；示例: %s", a.settings.PreferredPort, a.settings.PortScanEnd, strings.Join(occupied, ", "))
}

func (a *app) startAndConfigure() (returnErr error) {
	if _, err := os.Stat(a.paths.Backend); err != nil {
		return fmt.Errorf("缺少网关程序 %s: %w", a.paths.Backend, err)
	}
	accounts, errAccounts := countAntigravityAccounts(a.paths.AuthDir)
	if errAccounts != nil {
		return errAccounts
	}
	if accounts == 0 {
		return fmt.Errorf("没有有效 Antigravity 账号；请先运行 login 命令或平台登录脚本")
	}
	startedPID := 0
	configurationComplete := false
	defer func() {
		if returnErr == nil || startedPID <= 0 || configurationComplete {
			return
		}
		if errStop := terminateOwnedProcess(startedPID, a.paths.Backend); errStop != nil {
			returnErr = errors.Join(returnErr, fmt.Errorf("回收启动失败后的网关: %w", errStop))
			return
		}
		current, errState := a.loadState()
		if errState == nil && current.PID == startedPID {
			current.PID = 0
			if errSave := a.saveState(current); errSave != nil {
				returnErr = errors.Join(returnErr, fmt.Errorf("清理失败启动状态: %w", errSave))
			}
		}
	}()
	port, reuse, err := a.chooseGatewayPort()
	if err != nil {
		return err
	}
	if reuse {
		var managementProbe managementAuthFiles
		if errManagement := a.managementJSON(port, http.MethodGet, "/v0/management/auth-files", nil, &managementProbe); errManagement != nil {
			current, errCurrent := a.loadState()
			if errCurrent != nil || current.PID <= 0 || strings.TrimSpace(current.BackendPath) == "" {
				return fmt.Errorf("正在运行的旧网关不支持额度界面，且无法验证其进程所有权；请用控制中心安全停止后重试")
			}
			if errStop := terminateOwnedProcess(current.PID, current.BackendPath); errStop != nil {
				return fmt.Errorf("升级额度接口前停止旧网关: %w", errStop)
			}
			deadline := time.Now().Add(5 * time.Second)
			for !isPortFree(port) && time.Now().Before(deadline) {
				time.Sleep(100 * time.Millisecond)
			}
			if !isPortFree(port) {
				port, err = chooseFreePort(a.settings.PreferredPort, a.settings.PortScanEnd)
				if err != nil {
					return err
				}
			}
			reuse = false
			current.PID = 0
			_ = a.saveState(current)
		}
	}
	if reuse {
		fmt.Printf("已复用正在运行的本地网关: %s\n", a.gatewayURL(port))
	} else {
		if port != a.settings.PreferredPort {
			fmt.Printf("默认端口 %d 已占用，自动改用 %d。\n", a.settings.PreferredPort, port)
		}
		if err := a.writeBackendConfig(port); err != nil {
			return fmt.Errorf("写入网关配置: %w", err)
		}
		if err := rotateManagedFile(a.paths.ConsoleLog, 10<<20, 3); err != nil {
			return fmt.Errorf("轮转网关控制台日志: %w", err)
		}
		pid, err := launchDetached(a.paths.Backend, []string{"-config", a.paths.Config, "-local-model"}, a.paths.Data, a.paths.ConsoleLog)
		if err != nil {
			return fmt.Errorf("启动网关: %w", err)
		}
		startedPID = pid
		if err := a.waitForGateway(port, 20*time.Second); err != nil {
			_ = terminateOwnedProcess(pid, a.paths.Backend)
			return fmt.Errorf("网关未就绪，已停止刚启动的进程；请查看 %s: %w", a.paths.ConsoleLog, err)
		}
		current := state{
			Port:           port,
			PID:            pid,
			BackendPath:    a.paths.Backend,
			StartedAt:      a.now().UTC(),
			Launcher:       version,
			LastHealthTime: a.now().UTC(),
		}
		if err := a.saveState(current); err != nil {
			_ = terminateOwnedProcess(pid, a.paths.Backend)
			return fmt.Errorf("保存状态失败，已停止网关: %w", err)
		}
		fmt.Printf("网关已启动: %s (PID %d)\n", a.gatewayURL(port), pid)
	}

	fmt.Println("正在等待模型目录加载（网络异常时最多约 35 秒）...")
	catalog, err := a.waitForModels(port, 35*time.Second)
	if err != nil {
		return err
	}
	models, err := selectZCodeModels(catalog)
	if err != nil {
		return err
	}
	backup, changed, err := a.configureZCode(port, models)
	if err != nil {
		return err
	}
	current, _ := a.loadState()
	current.Port = port
	current.BackendPath = a.paths.Backend
	current.ZCodeConfig = a.paths.ZCodeConfig
	current.Models = modelIDs(models)
	current.LastHealthTime = a.now().UTC()
	current.Launcher = version
	if backup != "" {
		current.ZCodeBackup = backup
	}
	configurationComplete = true
	if err := a.saveState(current); err != nil {
		return fmt.Errorf("保存最终状态: %w", err)
	}
	if changed {
		fmt.Printf("ZCode Provider 已写入并备份原配置: %s\n", backup)
		fmt.Println("请完全退出并重新打开 ZCode，然后选择 Antigravity (Local Bridge) 模型。")
	} else {
		fmt.Println("ZCode Provider 已是最新配置。")
	}
	fmt.Printf("已同步 %d 个模型。\n", len(models))
	return nil
}

func (a *app) waitForGateway(port int, timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	var lastErr error
	for time.Now().Before(deadline) {
		if err := a.probeGateway(port); err == nil {
			return nil
		} else {
			lastErr = err
		}
		time.Sleep(250 * time.Millisecond)
	}
	if lastErr == nil {
		lastErr = errors.New("等待超时")
	}
	return lastErr
}

func (a *app) waitForModels(port int, timeout time.Duration) ([]modelInfo, error) {
	deadline := time.Now().Add(timeout)
	var lastErr error
	for {
		models, err := a.fetchModels(port)
		if err == nil && len(models) > 0 {
			return models, nil
		}
		if err != nil {
			lastErr = err
		}
		if time.Now().After(deadline) {
			if lastErr != nil {
				return nil, lastErr
			}
			return nil, fmt.Errorf("模型目录在 %s 内仍为空；请检查账号、代理和 %s", timeout.Round(time.Second), a.paths.ConsoleLog)
		}
		time.Sleep(time.Second)
	}
}

func (a *app) login() error {
	if _, err := os.Stat(a.paths.Backend); err != nil {
		return fmt.Errorf("缺少网关程序 %s: %w", a.paths.Backend, err)
	}
	port := a.settings.PreferredPort
	if current, err := a.loadState(); err == nil && current.Port >= a.settings.PreferredPort && current.Port <= a.settings.PortScanEnd {
		port = current.Port
	}
	if err := a.writeBackendConfig(port); err != nil {
		return fmt.Errorf("准备登录配置: %w", err)
	}
	callbackPort, err := chooseFreePort(a.settings.CallbackPreferredPort, a.settings.CallbackScanEnd)
	if err != nil {
		return fmt.Errorf("OAuth 回调端口 %d-%d 全部被占用", a.settings.CallbackPreferredPort, a.settings.CallbackScanEnd)
	}
	if callbackPort != a.settings.CallbackPreferredPort {
		fmt.Printf("OAuth 默认回调端口 %d 已占用，自动改用 %d。\n", a.settings.CallbackPreferredPort, callbackPort)
	}
	fmt.Println("浏览器将打开 Google 登录页。授权完成前请不要关闭此窗口。")
	started := a.now()
	var captured bytes.Buffer
	cmd := exec.Command(a.paths.Backend, "-config", a.paths.Config, "-antigravity-login", "-oauth-callback-port", strconv.Itoa(callbackPort))
	cmd.Dir = a.paths.Data
	if browserPath := preferredBrowserExecutable(); browserPath != "" {
		cmd.Env = append(os.Environ(), "CLIPROXY_BROWSER="+browserPath)
	}
	if a.guiMode {
		// A GUI launch may have no valid console handles. OAuth still opens the browser,
		// while all child output is
		// retained in memory for the same explicit success check below.
		cmd.Stdout = &captured
		cmd.Stderr = &captured
	} else {
		cmd.Stdin = os.Stdin
		cmd.Stdout = io.MultiWriter(os.Stdout, &captured)
		cmd.Stderr = io.MultiWriter(os.Stderr, &captured)
	}
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("OAuth 登录进程失败: %w", err)
	}
	if !strings.Contains(captured.String(), "Antigravity authentication successful!") {
		return fmt.Errorf("登录程序未确认成功，请检查上方输出")
	}
	if !hasRecentAntigravityAccount(a.paths.AuthDir, started.Add(-2*time.Second)) {
		return fmt.Errorf("登录程序报告成功，但未找到新凭据文件；不会继续覆盖 ZCode 配置")
	}
	fmt.Printf("Antigravity 登录成功。凭据只保存在当前用户目录: %s\n", a.paths.AuthDir)
	return nil
}

func hasRecentAntigravityAccount(dir string, since time.Time) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, entry := range entries {
		name := strings.ToLower(entry.Name())
		if entry.IsDir() || !strings.HasPrefix(name, "antigravity-") || !strings.HasSuffix(name, ".json") {
			continue
		}
		if info, err := entry.Info(); err == nil && !info.ModTime().Before(since) {
			return true
		}
	}
	return false
}

func (a *app) syncZCode() error {
	current, err := a.loadState()
	if err != nil {
		return err
	}
	if current.Port == 0 {
		return fmt.Errorf("尚无运行状态，请先启动网关")
	}
	if err := a.probeGateway(current.Port); err != nil {
		return fmt.Errorf("网关未运行: %w", err)
	}
	accounts, errAccounts := countAntigravityAccounts(a.paths.AuthDir)
	if errAccounts != nil {
		return errAccounts
	}
	if accounts == 0 {
		return fmt.Errorf("没有 Antigravity 账号，请先运行 login 命令或平台登录脚本")
	}
	catalog, err := a.waitForModels(current.Port, 35*time.Second)
	if err != nil {
		return err
	}
	models, err := selectZCodeModels(catalog)
	if err != nil {
		return err
	}
	backup, changed, err := a.configureZCode(current.Port, models)
	if err != nil {
		return err
	}
	current.Models = modelIDs(models)
	current.ZCodeConfig = a.paths.ZCodeConfig
	current.LastHealthTime = a.now().UTC()
	if backup != "" {
		current.ZCodeBackup = backup
	}
	if err := a.saveState(current); err != nil {
		return fmt.Errorf("保存同步状态: %w", err)
	}
	if changed {
		fmt.Printf("已同步 %d 个模型；备份: %s\n", len(models), backup)
		fmt.Println("请重启 ZCode 使配置生效。")
	} else {
		fmt.Printf("配置无需修改，当前有 %d 个模型。\n", len(models))
	}
	return nil
}

func (a *app) status() error {
	current, err := a.loadState()
	if err != nil {
		return err
	}
	accounts, accountErr := countAntigravityAccounts(a.paths.AuthDir)
	if accountErr != nil {
		return accountErr
	}
	fmt.Printf("程序目录: %s\n", a.paths.Root)
	fmt.Printf("Antigravity 账号文件: %d\n", accounts)
	if current.Port == 0 {
		fmt.Println("网关状态: 未启动")
		return fmt.Errorf("没有已记录的网关端口")
	}
	fmt.Printf("记录端口: %d\n", current.Port)
	if err := a.probeGateway(current.Port); err != nil {
		fmt.Printf("网关状态: 不健康 (%v)\n", err)
		return err
	}
	catalog, err := a.fetchModels(current.Port)
	if err != nil {
		return err
	}
	models, err := selectZCodeModels(catalog)
	if err != nil {
		return err
	}
	fmt.Printf("网关状态: 正常 %s\n", a.gatewayURL(current.Port))
	fmt.Printf("ZCode 可选模型: %d\n", len(models))
	for _, model := range models {
		fmt.Printf("  - %s\n", model.ID)
	}
	configured, baseURL, err := zcodeProviderStatus(a.paths.ZCodeConfig)
	if err != nil {
		fmt.Printf("ZCode Provider: 无法读取 (%v)\n", err)
	} else if configured {
		fmt.Printf("ZCode Provider: 已配置 (%s)\n", baseURL)
	} else {
		fmt.Println("ZCode Provider: 未配置")
	}
	return nil
}

type smokeAudit struct {
	Timestamp      time.Time `json:"timestamp"`
	RequestedModel string    `json:"requestedModel"`
	ResponseModel  string    `json:"responseModel,omitempty"`
	ResponseID     string    `json:"responseID,omitempty"`
	OutputText     string    `json:"outputText"`
}

const smokeExpectedOutput = "ZCODE_SMOKE_OK"

func (a *app) smokeModel(model string) error {
	model = strings.TrimSpace(model)
	if model == "" {
		return fmt.Errorf("模型 ID 不能为空")
	}
	if !isAllowedZCodeModel(model) {
		return fmt.Errorf("模型 %q 不在允许列表；仅支持 %s", model, strings.Join(zcodeModelAllowlist, ", "))
	}
	current, errState := a.loadState()
	if errState != nil {
		return errState
	}
	if current.Port <= 0 {
		return fmt.Errorf("网关尚未启动")
	}
	if err := a.probeGateway(current.Port); err != nil {
		return fmt.Errorf("网关未运行: %w", err)
	}
	models, errModels := a.fetchModels(current.Port)
	if errModels != nil {
		return errModels
	}
	found := false
	for _, available := range models {
		if available.ID == model {
			found = true
			break
		}
	}
	if !found {
		return fmt.Errorf("模型目录中不存在精确 ID %q", model)
	}
	payload := map[string]any{
		"model":      model,
		"max_tokens": 256,
		"stream":     false,
		"messages": []map[string]any{{
			"role":    "user",
			"content": "Reply with exactly: " + smokeExpectedOutput,
		}},
	}
	body, errJSON := json.Marshal(payload)
	if errJSON != nil {
		return errJSON
	}
	request, errRequest := http.NewRequest(http.MethodPost, a.gatewayURL(current.Port)+"/v1/messages", bytes.NewReader(body))
	if errRequest != nil {
		return errRequest
	}
	request.Header.Set("Content-Type", "application/json")
	request.Header.Set("x-api-key", a.apiKey)
	request.Header.Set("Authorization", "Bearer "+a.apiKey)
	request.Header.Set("anthropic-version", "2023-06-01")
	request.Header.Set("User-Agent", "ZCode-Antigravity-Bridge/"+version)
	response, errDo := httpClient(90 * time.Second).Do(request)
	if errDo != nil {
		return fmt.Errorf("真实模型请求失败: %w", errDo)
	}
	defer response.Body.Close()
	responseBody, errRead := io.ReadAll(io.LimitReader(response.Body, 8<<20))
	if errRead != nil {
		return errRead
	}
	if response.StatusCode != http.StatusOK {
		return fmt.Errorf("真实模型请求返回 HTTP %d: %s", response.StatusCode, compactText(responseBody, 600))
	}
	var decoded struct {
		ID      string `json:"id"`
		Model   string `json:"model"`
		Content []struct {
			Type string `json:"type"`
			Text string `json:"text"`
		} `json:"content"`
	}
	if err := json.Unmarshal(responseBody, &decoded); err != nil {
		return fmt.Errorf("真实模型响应不是 Anthropic JSON: %w", err)
	}
	parts := make([]string, 0, len(decoded.Content))
	for _, content := range decoded.Content {
		if content.Type == "text" && strings.TrimSpace(content.Text) != "" {
			parts = append(parts, strings.TrimSpace(content.Text))
		}
	}
	output := strings.Join(parts, "\n")
	if output == "" {
		return fmt.Errorf("真实模型响应没有文本内容")
	}
	if output != smokeExpectedOutput {
		return fmt.Errorf("真实模型响应未通过精确输出校验: %q", compactText([]byte(output), 200))
	}
	audit := smokeAudit{
		Timestamp:      a.now().UTC(),
		RequestedModel: model,
		ResponseModel:  decoded.Model,
		ResponseID:     decoded.ID,
		OutputText:     output,
	}
	auditRaw, errAudit := json.MarshalIndent(audit, "", "  ")
	if errAudit != nil {
		return errAudit
	}
	auditRaw = append(auditRaw, '\n')
	auditPath := filepath.Join(a.paths.Data, "last-smoke-test.json")
	if err := writeAtomic(auditPath, auditRaw, 0o600); err != nil {
		return fmt.Errorf("保存冒烟测试审计: %w", err)
	}
	fmt.Printf("真实模型请求成功: requested=%s response=%s id=%s\n", model, decoded.Model, decoded.ID)
	fmt.Printf("模型输出: %s\n", output)
	fmt.Printf("审计文件: %s\n", auditPath)
	return nil
}

func (a *app) doctor() error {
	problems := make([]string, 0)
	if info, err := os.Stat(a.paths.Backend); err != nil {
		problems = append(problems, "缺少 backend/"+filepath.Base(a.paths.Backend))
	} else if info.IsDir() || info.Size() < 1<<20 {
		problems = append(problems, "网关二进制大小异常")
	} else {
		fmt.Printf("[OK] 网关二进制: %s (%d bytes)\n", a.paths.Backend, info.Size())
	}
	if raw, err := os.ReadFile(a.paths.ZCodeConfig); err != nil {
		problems = append(problems, "找不到 ZCode 配置；请先安装并运行一次 ZCode")
	} else {
		var parsed map[string]any
		if json.Unmarshal(raw, &parsed) != nil {
			problems = append(problems, "ZCode config.json 已损坏，程序不会覆盖它")
		} else {
			fmt.Printf("[OK] ZCode 配置: %s\n", a.paths.ZCodeConfig)
		}
	}
	if a.settings.ProxyURL == "" {
		fmt.Println("[INFO] 未设置专用代理；会继承当前系统的 HTTP_PROXY/HTTPS_PROXY 环境变量。")
	} else {
		fmt.Printf("[OK] 专用代理: %s\n", redactURLUserinfo(a.settings.ProxyURL))
	}
	if isPortFree(a.settings.PreferredPort) {
		fmt.Printf("[OK] 默认 API 端口 %d 当前可用\n", a.settings.PreferredPort)
	} else {
		fmt.Printf("[INFO] 默认 API 端口 %d 已占用，启动时会自动换端口 (%s)\n", a.settings.PreferredPort, describePortOwner(a.settings.PreferredPort))
	}
	if len(problems) > 0 {
		for _, problem := range problems {
			fmt.Printf("[ERROR] %s\n", problem)
		}
		return fmt.Errorf("发现 %d 个问题", len(problems))
	}
	fmt.Println("本机静态检查通过。")
	return nil
}

func redactURLUserinfo(value string) string {
	u, err := urlParse(value)
	if err != nil || u.User == nil {
		return value
	}
	u.User = urlUser("***")
	return u.String()
}

// Indirections keep the redaction helper easy to test without exposing credentials.
var (
	urlParse = func(value string) (*url.URL, error) { return url.Parse(value) }
	urlUser  = url.User
)

func (a *app) stop() error {
	current, err := a.loadState()
	if err != nil {
		return err
	}
	if current.PID <= 0 {
		return fmt.Errorf("没有本程序记录的网关 PID；为避免误杀其他进程，不会按端口强制停止")
	}
	if current.Port <= 0 || a.probeGateway(current.Port) != nil {
		return fmt.Errorf("记录的 PID/端口无法通过网关身份校验；为避免 PID 重用误杀，不会停止")
	}
	expected := current.BackendPath
	if expected == "" {
		expected = a.paths.Backend
	}
	if err := terminateOwnedProcess(current.PID, expected); err != nil {
		return err
	}
	deadline := time.Now().Add(8 * time.Second)
	for time.Now().Before(deadline) {
		if a.probeGateway(current.Port) != nil {
			break
		}
		time.Sleep(200 * time.Millisecond)
	}
	if a.probeGateway(current.Port) == nil {
		return fmt.Errorf("进程已请求停止，但端口仍由兼容网关占用")
	}
	current.PID = 0
	if err := a.saveState(current); err != nil {
		return err
	}
	fmt.Printf("网关已停止，保留端口 %d 供下次启动复用。\n", current.Port)
	return nil
}

// Used by tests to ensure long-running child commands can be cancelled cleanly.
func commandContext(ctx context.Context, name string, args ...string) *exec.Cmd {
	return exec.CommandContext(ctx, name, args...)
}
